server:
  port: 9960

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bitdb
    username: oljc
    password: ljc.byte
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password: ljc@redis
      timeout: 1000ms
      lettuce:
        pool:
          max-active: 32
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms
        shutdown-timeout: 200ms
      connect-timeout: 1000ms
      command-timeout: 1000ms

  # 缓存配置
  cache:
    type: redis
    redis:
      time-to-live: 10m  # 10分钟
      cache-null-values: false

  security:
    user:
      name: oljc
      password: ljc.byte
      roles: ADMIN

# JWT 配置
app:
  jwt:
    secret: your-super-secret-jwt-key-with-at-least-32-characters-length-for-security
    issuer: arco-serve
    audience: arco-client
    access-token-expiration: PT15M    # 15分钟
    refresh-token-expiration: P7D     # 7天
