name: 🐛 Bug 报告
description: 报告 arco-serve 项目中的 Bug 或异常行为
title: "[Bug]: "
labels: ["🐛 bug", "pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您为 arco-serve 项目报告 Bug！请填写以下详细信息，以帮助我们快速定位和修复问题。

        - 请将问题标题格式化为：`[类型]：简短描述` （例如：`[Bug]：创建用户时返回500错误`）
        - 在提交之前，请检查是否已存在类似的问题
        - 如果可能，请提供相关的日志输出、错误堆栈信息或请求响应示例

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 发生了什么异常行为？期望的正确结果是什么？
      placeholder: |
        请详细描述遇到的问题，包括：
        - 具体的错误现象
        - 期望的正确行为
        - 影响范围（如：特定API、整个服务等）
    validations:
      required: true

  - type: textarea
    id: extra
    attributes:
      label: 补充信息 (可选)
      description: 请提供相关的环境信息、错误日志、堆栈信息等，以帮助定位问题。
      placeholder: |
        **运行环境:**
        - 操作系统: macOS 14.0 / Ubuntu 22.04 / Windows 11

        **错误日志:**
        ```
        请粘贴相关的错误日志或堆栈信息
        ```

        **请求/响应示例:**
        ```json
        请求：POST /api/users
        响应：{"error": "Internal Server Error", "status": 500}
        ```

  - type: checkboxes
    id: checklist
    attributes:
      label: 核对清单
      description: 在提交问题之前，请确保您已完成以下操作。
      options:
        - label: 我已经搜索过现有的 Issues，确认没有重复的 Bug 报告。
          required: true
        - label: 我已经提供了清晰且可重现的步骤或请求示例。
          required: true
        - label: 我确定这是 arco-serve 后端服务的问题，而非客户端或网络问题。
          required: true
