name: 依赖安全检查

on:
  schedule:
    # 每周一早上8点运行
    - cron: '0 8 * * 1'
  push:
    branches: [ main ]
    paths:
      - 'build.gradle'
      - 'gradle/wrapper/gradle-wrapper.properties'
  pull_request:
    paths:
      - 'build.gradle'
      - 'gradle/wrapper/gradle-wrapper.properties'

jobs:
  dependency-check:
    name: OWASP 依赖检查
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: 缓存 Gradle 依赖
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: 授予 gradlew 执行权限
      run: chmod +x gradlew

    - name: 运行 OWASP 依赖检查
      run: ./gradlew dependencyCheckAnalyze
      continue-on-error: true

    - name: 上传依赖检查报告
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-check-report
        path: build/reports/dependency-check-report.html
        retention-days: 7

  audit-dependencies:
    name: 依赖审计
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置 Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: 缓存 Gradle 依赖
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: 授予 gradlew 执行权限
      run: chmod +x gradlew

    - name: 生成依赖报告
      run: ./gradlew dependencies > dependencies.txt

    - name: 检查过期依赖
      run: ./gradlew dependencyUpdates

    - name: 上传依赖报告
      uses: actions/upload-artifact@v4
      with:
        name: dependency-reports
        path: |
          dependencies.txt
          build/dependencyUpdates/
        retention-days: 7
