name: Lint PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            refactor
            docs
            chore
            perf
            revert
            release
            test
            style
          requireScope: false
          disallowScopes: |
            [A-Z]+
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            你好，在PR标题 "{title}" 中发现 "{subject}" 不符合本项目规范要求。
            请确保主题不以大写字母开头。
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: false